# release action with semantic release
name: Release

on:
  ## only manually release for now
  workflow_dispatch:

jobs:
  release:
    name: Release to Github
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Compress files
        run: npm run compress-samext
      - name: Zip files
        run: npm run zip
      - name: Semantic Release
        run: npx semantic-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
