name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Release to Github
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Compress files
        run: npm run compress-samext
      - name: Zip Chrome extension
        run: npm run zip
      - name: Build Safari extension
        run: |
          # Convert Chrome extension to Safari using Apple's converter
          xcrun safari-web-extension-converter . \
            --app-name "samext-safari" \
            --bundle-identifier "co.samser.samext.safari" \
            --macos-only \
            --no-open \
            --force
          
          cd samext-safari
          xcodebuild -scheme samext-safari -configuration Release -derivedDataPath ./DerivedData
          
          cd DerivedData/Build/Products/Release
          ditto -c -k --sequesterRsrc --keepParent samext-safari.app ../../../../samext-safari.zip
      - name: Semantic Release
        run: npx semantic-release
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
